//------------------------------------------------------------------------------
//
// File Name:	Precompiled.cpp
// Author(s):	Doug Schilling (dschilling), original version auto-generated by Visual Studio
// Course:		CS529F25
// Project:		Project 0
// Purpose:		This file is used to generate the precompiled header file (Precompiled.h).
//   When using precompiled headers:
//     - Exactly one .c/.cpp file must be used to generate the PCH with the "Create (/Yc)" project setting.
//     - All other .c/.cpp files must be set to use the PCH with the "Use (/Yu)" project setting.
//
// Copyright © 2025 DigiPen (USA) Corporation.
//
//------------------------------------------------------------------------------

#include "Precompiled.h"