//------------------------------------------------------------------------------
//
// File Name:	Precompiled.h
// Author(s):	Doug Schilling (dschilling), original version auto-generated by Visual Studio
// Project:		Project 0
// Course:		CS529F25
// Purpose:		This file includes standard system include files, or project-specific 
//   include files that are used frequently, but are changed infrequently.
//   When using precompiled headers:
//     - Exactly one .c/.cpp file must be set to generate the PCH with the "Create (/Yc)" project setting.
//     - All other .c/.cpp files must be set to use the PCH with the "Use (/Yu)" project setting.
//
// Copyright © 2025 DigiPen (USA) Corporation.
//
//------------------------------------------------------------------------------

#pragma once

#include "targetver.h"

// Windows Header Files
#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers
#define NOMINMAX				// Disable the Windows.h versions of min/max.
#include <windows.h>

// C RunTime Header Files
#include <algorithm>
#include <cassert>
#include <malloc.h>
#include <memory.h>
#include <sal.h>
#include <stdlib.h>
#include <string_view>
#include <tchar.h>
#include <vector>

// 3rd-Party Libraries
#include <DGL/inc/DGL.h>

#include <dragon/logging/Level.h>
#include <dragon/logging/Logger.h>
#include <dragon/logging/DebugChannel.h>
#include <dragon/logging/MultiplexChannel.h>
#include <dragon/logging/TextFileChannel.h>
#include <dragon/platform_dependencies.h>

#include <nlohmann/json.hpp>
